main:
  - name: "Code of Conduct"
    url: /conduct/
    weight: 5
  - name: Speakers
    url: /sessions/
    weight: 3
  - name: "Join the Community"
    url: /join/
    weight: 7

sessions:
  - name: "Overview"
    weight: 1
  - name: "Keynote"
    weight: 2