main:
  - name: "Register"
    url: "TBD"
    weight: 1
  - name: "Code of Conduct"
    url: /conduct/
    weight: 2
  - name: "2023 Speakers"
    url: /sessions_2023/
    weight: 1
  - name: "Sponsors and Organizers"
    url: /sponsors/
    weight: 3
  - name: "Join the Community"
    url: /join/
    weight: 4
  - name: "2022 Speakers"
    url: /sessions_2022/
    weight: 5

sessions_2022:
  - name: "Overview"
    weight: 1
  - name: "Keynote"
    weight: 2
  - name: "Concurrent Speakers"
    weight: 3
  - name: "Data Blitz"
    weight: 4
  - name: "Panels"
    weight: 5
  - name: "Breaks"
    weight: 6
  - name: "Closing"
    weight: 7
    
sessions_2021:
  - name: "Overview"
    weight: 1
  - name: "Keynote"
    weight: 2
  - name: "Concurrent Speakers"
    weight: 3
  - name: "Data Blitz"
    weight: 4
  - name: "Panels"
    weight: 5
  - name: "Networking"
    weight: 6 
