main:
  - name: "Code of Conduct"
    url: /conduct/
    weight: 5
  - name: "Speakers"
    url: /sessions_2022/
    weight: 3
  - name: "Join the Community"
    url: /join/
    weight: 7

sessions_2022:
  - name: "Overview"
    weight: 1
  - name: "Keynote"
    weight: 2
  - name: "Concurrent Speakers"
    weight: 3
  - name: "Data Blitz"
    weight: 4
  - name: "Panels"
    weight: 5
  - name: "Networking"
    weight: 6